/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouwei_jnisample1_business_JNIDemo */

#ifndef _Included_com_zhouwei_jnisample1_business_JNIDemo
#define _Included_com_zhouwei_jnisample1_business_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
