/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouwei_jnisample1_business_JNIDemo */

#ifndef _Included_com_zhouwei_jnisample1_business_JNIDemo
#define _Included_com_zhouwei_jnisample1_business_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getByte
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getChar
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getShort
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getInt
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getFloat
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getDouble
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test1
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test1
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test2
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test2
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test3
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test3
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test4
 * Signature: (SI)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test4
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test44
 * Signature: (SI)I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test44
  (JNIEnv *, jobject, jshort, jint);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test5
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test5
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test55
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test55
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test555
 * Signature: (Lcom/zhouwei/jnisample1/business/Student;)Lcom/zhouwei/jnisample1/business/Student;
 */
JNIEXPORT jobject JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test555
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIDemo
 * Method:    test5555
 * Signature: (Lcom/zhouwei/jnisample1/business/Student;)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_JNIDemo_test5555
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
