/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouwei_jnisample1_business_JNIMath */

#ifndef _Included_com_zhouwei_jnisample1_business_JNIMath
#define _Included_com_zhouwei_jnisample1_business_JNIMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhouwei_jnisample1_business_JNIMath
 * Method:    Add
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample1_business_JNIMath_Add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIMath
 * Method:    Sub
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample1_business_JNIMath_Sub
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIMath
 * Method:    Mul
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample1_business_JNIMath_Mul
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_zhouwei_jnisample1_business_JNIMath
 * Method:    Div
 * Signature: (DD)I
 */
JNIEXPORT jint JNICALL Java_com_zhouwei_jnisample1_business_JNIMath_Div
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
