/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouwei_jnisample1_business_C_Callback_Java */

#ifndef _Included_com_zhouwei_jnisample1_business_C_Callback_Java
#define _Included_com_zhouwei_jnisample1_business_C_Callback_Java
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhouwei_jnisample1_business_C_Callback_Java
 * Method:    getInfo
 * Signature: (Lcom/zhouwei/jnisample1/business/C_Callback_Java/CallBack;)V
 */
JNIEXPORT void JNICALL Java_com_zhouwei_jnisample1_business_C_1Callback_1Java_getInfo
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
