/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouwei_jnisample1_business_C_Callback_Java_CallBack */

#ifndef _Included_com_zhouwei_jnisample1_business_C_Callback_Java_CallBack
#define _Included_com_zhouwei_jnisample1_business_C_Callback_Java_CallBack
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
